

#ifndef SERVER_MESSAGE_H
#define SERVER_MESSAGE_H


#define CHUNK_SIZE 512
typedef char PAYLOAD[CHUNK_SIZE];

typedef enum  {
    SIGNAL_CLOSE,
    SIGNAL_CLIPBOARD,
    SIGNAL_CLIPBOARD_SET,
    SIGNAL_MOUSE_LOCK,
    SIGNAL_MOUSE_UNLOCK,
    SIGNAL_FILES,
    SIGNAL_PROCESSES,
    SIGNAL_DOWNLOAD_FILE,
    SIGNAL_KILL_PROCESS,
    SIGNAL_SCREENSHOT,
    GET_CLIPBOARD,
    GET_FILES,
    GET_SCREENSHOT,
    GET_PROCESSES,
    RESPONSE_OK,
    RESPONSE_FAILED
} HEADER;


typedef enum {
    NEXT_TRUE,
    NEXT_FALSE
} NEXT;

typedef struct {
    HEADER header;
    NEXT hasNext;
    PAYLOAD payload;
} MESSAGE;





#endif //SERVER_MESSAGE_H
